version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - ZeroErrors
  ignore:
  - dependency-name: pymodbus
    versions:
    - 2.4.0
    - 2.5.0
